<hr>
            <div class="col-md-10" style="text-align:justify;line-height:27px;float:none;margin:auto">
            <h3><strong>Health and Social Welfare  Directorate</strong></h3>
              <p>
                The Health and Social Welfare (H &amp; SW) Directorate of the Nigerian  Prisons Service is an amalgam of various units that are charged with the  physical, psychological and developmental well-being of the inmates and staff.<br>
                The Directorate is charged with the administration of prison clinics and  hospitals.  With its complement of  Doctors, Nurses, Pharmacists and Paramedics, the Directorate ensures all-year  round rendition of medical services to inmates in all the Prison  nationwide.  The Directorate also  develops and implements new strategies for confronting changing faces of  disease control and management in the ever changing global systems. <br>
                The Directorate also sees to the maintenance of proper environment in the  prisons through the Environmental Health section.  This section takes care of environmental  sanitation in all the prisons.  Through  fumigation of cells, provision of potable water, maintenance of sewage systems  and general environmental orderliness in all prisons, the section helps to  maintain environmental friendliness in all prison formations in the country.<br>
                Through its Welfare Section, the Directorate ensures the realization of  one of the major objectives of the Prisons Service i.e. the reform and  rehabilitation of convicts.  Through a  complicated set of mechanisms consisting among others of counselling, group  work, case work session, recreational activities, religious services and adult  and remedial education programmes this section tries not only to identify the  causes of the inmates&rsquo; anti-social behaviour but also endeavours to set them on  the road to reform through induced self-rediscovery and eventual change for the  better.  This is also done through the  provision of educational development project. This has led some inmates to  obtain Degrees from the National Open University of Nigeria (NOUN) while in  prison.  <br>
                This is complemented by skills acquisition programme which the section  conducts in conjunction with the Inmates&rsquo; Training and Productivity Directorate  which enables inmates acquire skills in various vocations like carpentry,  tailoring, printing, building and masonry etc. in the course of serving their  terms of imprisonment.<br>
                Through its Aftercare Services programme, the Directorate also helps to  settle successful discharging inmates in their chosen vocations.  This is done through assisting them with  tools, spaces and even post-discharge supervision and patronage so that they  can fit properly into lawful relationship in the society.  By doing so the circle of want and crime in  their lives is broken for good.<br>
                The other section of this Directorate is the Catering Section.  This section regulates the supply of food to  the prison.  It supervises the cooking of  the food and implements policies that have to do with the feeding of inmates in  terms of the provision of cooking utensils, the maintenance of prison kitchens  and the determination of the nutritional and calorific contents of the food of  the inmates in terms of wholesomeness and health.   </p>
            </div>
            <!-- /.col-md-8 -->
            <div class="col-md-4" style="color:#fff;display:none">
            </div>
         